"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/astronaut.glb -t 
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import type { ThreeElements } from '@react-three/fiber';

type ActionName = 'Idle'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cube001_0: THREE.SkinnedMesh
    Cube005_0: THREE.SkinnedMesh
    Cube002_0: THREE.SkinnedMesh
    Plane_0: THREE.SkinnedMesh
    Cube008_0: THREE.SkinnedMesh
    Cube004_0: THREE.SkinnedMesh
    Cube003_0: THREE.SkinnedMesh
    Cube_0: THREE.SkinnedMesh
    Cube009_0: THREE.SkinnedMesh
    Cube011_0: THREE.SkinnedMesh
    metarig_rootJoint: THREE.Bone
  }
  materials: {
    ['AstronautFallingTexture.png']: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: ThreeElements['group']) {
  const group = React.useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/models/astronaut.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group as React.RefObject<THREE.Group>)
  useEffect(()=>{
    if(animations.length > 0){
      actions[animations[0].name]?.play();
    }
  },[actions,animations]);

  useFrame((state, delta) => {
  if (!group.current) return;

  // falling movement
  group.current.position.y = THREE.MathUtils.lerp(
    group.current.position.y,
    -0.5,
    1.5 * delta
  );
  group.current.position.x = THREE.MathUtils.lerp(
    group.current.position.x,
    -0.5,
    1.5 * delta
  );

  // tiny floating rotation
  group.current.rotation.z = Math.sin(state.clock.elapsedTime * 1.3) * 0.05;

  // small falling tilt
  group.current.rotation.x = THREE.MathUtils.lerp(
    group.current.rotation.x,
    0.45,
    1.5 * delta
  );
});

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.193}>
          <group name="Root">
            <group name="metarig">
              <primitive object={nodes.metarig_rootJoint} />
              <group name="Cube001" />
              <group name="Cube005" />
              <group name="Cube002" />
              <group name="Plane" />
              <group name="Cube008" />
              <group name="Cube004" />
              <group name="Cube003" />
              <group name="Cube" />
              <group name="Cube009" rotation={[-2.708, 0.013, -1.447]} scale={1.307} />
              <group name="Cube011" />
              <skinnedMesh name="Cube001_0" geometry={nodes.Cube001_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube001_0.skeleton} />
              <skinnedMesh name="Cube005_0" geometry={nodes.Cube005_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube005_0.skeleton} />
              <skinnedMesh name="Cube002_0" geometry={nodes.Cube002_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube002_0.skeleton} />
              <skinnedMesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Plane_0.skeleton} />
              <skinnedMesh name="Cube008_0" geometry={nodes.Cube008_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube008_0.skeleton} />
              <skinnedMesh name="Cube004_0" geometry={nodes.Cube004_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube004_0.skeleton} />
              <skinnedMesh name="Cube003_0" geometry={nodes.Cube003_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube003_0.skeleton} />
              <skinnedMesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube_0.skeleton} />
              <skinnedMesh name="Cube009_0" geometry={nodes.Cube009_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube009_0.skeleton} />
              <skinnedMesh name="Cube011_0" geometry={nodes.Cube011_0.geometry} material={materials['AstronautFallingTexture.png']} skeleton={nodes.Cube011_0.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
